------------------------- MODULE SeatLimitTraceLog -------------------------
(*
 * GENERATED by scripts/trace-to-tla.sh from
 * usecases/write-skew-seat-limit/traces/*.json -- do not edit by hand.
 *
 * Each definition is one production log projected onto <<op, txn>>, which is
 * all of a log line SeatLimitTrace.tla can replay. See the use case README:
 * usecases/write-skew-seat-limit/README.md
 *)

\* Two invites, sequential. The second one saw the first seat taken and
\* was denied by the handler's guard. This is what a healthy day looks
\* like.
HealthyLog ==
  << [op |-> "select", txn |-> "t1"],
     [op |-> "insert", txn |-> "t1"],
     [op |-> "commit", txn |-> "t1"],
     [op |-> "select", txn |-> "t2"],
     [op |-> "deny", txn |-> "t2"]
  >>

\* INC-2291. Two admins clicked Invite inside the same 40ms. Both requests
\* returned 201 and the org finished with two members on a one-seat plan.
\* Ops maintain the pool is set to SERIALIZABLE.
IncidentLog ==
  << [op |-> "select", txn |-> "t1"],
     [op |-> "insert", txn |-> "t1"],
     [op |-> "select", txn |-> "t2"],
     [op |-> "commit", txn |-> "t1"],
     [op |-> "insert", txn |-> "t2"],
     [op |-> "commit", txn |-> "t2"]
  >>

\* Same overlap as the incident, on a pool that really is SERIALIZABLE:
\* the second COMMIT came back 40001 serialization_failure and was rolled
\* back. The seat limit held.
RetriedLog ==
  << [op |-> "select", txn |-> "t1"],
     [op |-> "insert", txn |-> "t1"],
     [op |-> "select", txn |-> "t2"],
     [op |-> "commit", txn |-> "t1"],
     [op |-> "insert", txn |-> "t2"],
     [op |-> "abort", txn |-> "t2"]
  >>

=============================================================================
