#!/usr/bin/env bash
# Project the production logs in usecases/write-skew-seat-limit/traces/ onto the
# alphabet SeatLimitTrace.tla can replay, and write them out as one generated
# TLA+ module.
#
# Everything the model has no opinion about -- timestamps, SQL text, user ids,
# HTTP status, SQLSTATE -- is dropped here. That projection is the trust
# boundary of the whole T5 check: what this script throws away, the replay can
# never contradict.
#
#   ./scripts/trace-to-tla.sh           regenerate languages/tla/SeatLimitTraceLog.tla
#   ./scripts/trace-to-tla.sh --check   fail if the committed module is stale
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
traces_dir="${repo_root}/usecases/write-skew-seat-limit/traces"
out="${repo_root}/languages/tla/SeatLimitTraceLog.tla"

render() {
  cat <<'HEADER'
------------------------- MODULE SeatLimitTraceLog -------------------------
(*
 * GENERATED by scripts/trace-to-tla.sh from
 * usecases/write-skew-seat-limit/traces/*.json -- do not edit by hand.
 *
 * Each definition is one production log projected onto <<op, txn>>, which is
 * all of a log line SeatLimitTrace.tla can replay. See the use case README:
 * usecases/write-skew-seat-limit/README.md
 *)
HEADER

  local f base name
  for f in "${traces_dir}"/*.json; do
    base="$(basename "$f" .json)"
    # healthy.json -> HealthyLog
    name="$(printf '%s' "${base:0:1}" | tr '[:lower:]' '[:upper:]')${base:1}Log"
    echo
    jq -r '.note' "$f" | fold -s -w 72 | sed -e 's/[[:space:]]*$//' -e 's|^|\\* |'
    printf '%s ==\n' "$name"
    jq -r '"  << " + ([.events[] | "[op |-> \"\(.op)\", txn |-> \"\(.txn)\"]"] | join(",\n     ")) + "\n  >>"' "$f"
  done

  echo
  echo "============================================================================="
}

if [ "${1:-}" = "--check" ]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  render > "$tmp"
  if ! diff -u "$out" "$tmp"; then
    echo "error: languages/tla/SeatLimitTraceLog.tla is stale; run ./scripts/trace-to-tla.sh" >&2
    exit 1
  fi
  echo "== traces: SeatLimitTraceLog.tla matches traces/*.json"
else
  render > "$out"
  echo "wrote ${out}"
fi
